# Generated by Django 5.1.5 on 2025-02-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newblog', '0002_like_user_post_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='dislike',
            name='user_post_unique',
            field=models.CharField(default='000', max_length=500, unique=True),
        ),
    ]
