# Generated by Django 5.1.4 on 2025-01-25 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newblog', '0003_remove_post_id_alter_post_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': ['author']},
        ),
    ]
