# Generated by Django 5.1.4 on 2025-01-25 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newblog', '0005_alter_post_options_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='posts',
        ),
    ]
