# Generated by Django 5.1.5 on 2025-02-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newblog', '0006_rename_post_comment_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.BigIntegerField(default=0),
        ),
    ]
