# Generated by Django 5.1.5 on 2025-02-01 14:45

import func.saveimage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=func.saveimage.user_profile_image_path)),
            ],
        ),
    ]
